# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class UfcItem(scrapy.Item):
    fight_result = scrapy.Field()
    fight_class = scrapy.Field()
    fighter_name_1 = scrapy.Field()
    event_name = scrapy.Field()
    fighter_name_2 = scrapy.Field()
    kd_1 = scrapy.Field()
    kd_2 = scrapy.Field()
    sig_str_1 = scrapy.Field()
    sig_str_2 = scrapy.Field()
    sig_strP_1 = scrapy.Field()
    sig_strP_2 = scrapy.Field()
    tot_str_1 = scrapy.Field()
    tot_str_2 = scrapy.Field()
    TD_1 = scrapy.Field()
    TD_2 = scrapy.Field()
    TDP_1 = scrapy.Field()
    TDP_2 = scrapy.Field()
    sub_att_1 = scrapy.Field()
    sub_att_2 = scrapy.Field()
    rev_1 = scrapy.Field()
    rev_2 = scrapy.Field()
    ctrl_1 = scrapy.Field()
    ctrl_2 = scrapy.Field()
    r1_sig_str_1= scrapy.Field()
    r1_sig_str_2= scrapy.Field()
    r1_sig_strP_1 = scrapy.Field()
    r1_sig_strP_2 = scrapy.Field()
    r1_tot_str_1 = scrapy.Field()
    r1_tot_str_2 = scrapy.Field()
    r1_TD_1 = scrapy.Field()
    r1_TD_2 = scrapy.Field()
    r1_TDP_1 = scrapy.Field()
    r1_TDP_2 = scrapy.Field()
    r1_sub_att_1 = scrapy.Field()
    r1_sub_att_2 = scrapy.Field()
    r1_rev_1 = scrapy.Field()
    r1_rev_2 = scrapy.Field()
    r1_ctrl_1 = scrapy.Field()
    r1_ctrl_2 = scrapy.Field()
    method = scrapy.Field()
    round = scrapy.Field()
    time = scrapy.Field()
    time_format = scrapy.Field()
    referee = scrapy.Field()
    details = scrapy.Field()
    event_loc = scrapy.Field()
    event_date = scrapy.Field()
    judge_1 = scrapy.Field()
    judge_2 = scrapy.Field()
    judge_3 = scrapy.Field()
    tot_head_1 = scrapy.Field()
    tot_head_2 = scrapy.Field()
    tot_body_1 = scrapy.Field()
    tot_body_2 = scrapy.Field()
    tot_leg_1 = scrapy.Field()
    tot_leg_2 = scrapy.Field()
    tot_dist_1 = scrapy.Field()
    tot_dist_2 = scrapy.Field()
    tot_clinch_1 = scrapy.Field()
    tot_clinch_2 = scrapy.Field()
    tot_ground_1 = scrapy.Field()
    tot_ground_2 = scrapy.Field()
    f1_res = scrapy.Field()
    f2_res = scrapy.Field()

